# ===== SERVEUR =====
server.port=8081
spring.application.name=charite-app
# ===== BASE DE DONNEES POSTGRESQL (conteneur Docker) =====
# Supprime ou commente les lignes H2 precedentes
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5432/charite_db
spring.datasource.username=${DB_PROD_USERNAME}
spring.datasource.password=${DB_PROD_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.messages.basename=i18n/messages
# ===== MONGODB =====
spring.data.mongodb.uri=mongodb://localhost:27017/charite
spring.data.mongodb.database=charite
# ===== THYMELEAF =====
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
# ===== UPLOAD DE FICHIERS =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
file.upload-dir=uploads/
# ===== GOOGLE OAUTH 2.0 =====
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
# ===== STRIPE (mode test) =====
stripe.api.key=${STRIPE_TEST_SK}
stripe.publishable.key=${STRIPE_TEST_PK}
# ===== EMAIL (Gmail SMTP) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ===== LOGGING =====
logging.level.com.charite=DEBUG
logging.level.org.springframework.security=DEBUG

